dist: xenial

sudo: false

language: go

branches:
  only:
    - master

go:
  - 1.12.4

install: true

notifications:
  email: false

env:
  - GO111MODULE=on

services:
  - docker

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
  - docker --version

script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -v -race ./...  # run all the tests with the race detector enabled
