dist: xenial

sudo: false

language: go

go:
  - 1.12.4

install: true

notifications:
  email: false

env:
  # enforcing go mod in GOPATH
  - GO111MODULE=on

services:
  - docker

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
  - docker --version

script:
  - golangci-lint run # run a bunch of code checkers/linters in parallel
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./... # run all the tests with the race detector enabled

after_success:
  - bash <(curl -s https://codecov.io/bash)

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      all_branches: true
      condition: $TRAVIS_OS_NAME = linux
