dist: xenial

sudo: false

language: go

addons:
  apt:
    packages:
      # needed for the nfpm pipe:
      - rpm
      # needed for the snap pipe:
      - snapd

go:
  - 1.12.4

install: true

notifications:
  email: false

env:
  # needed for the snap pipe:
  # enforcing go mod in GOPATH
  - PATH=/snap/bin:$PATH GO111MODULE=on

services:
  - docker

before_script:
  # needed for the snap pipe:
  - sudo snap install snapcraft --classic
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint
  - docker --version

script:
  - golangci-lint run # run a bunch of code checkers/linters in parallel
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./... # run all the tests with the race detector enabled

after_success:
  - bash <(curl -s https://codecov.io/bash)

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      all_branches: true
      condition: $TRAVIS_OS_NAME = linux
